// packages/studio/src/components/costs/CostDashboard.vue
<script setup lang="ts">
import { useCosts } from "../../composables/useCosts";
import TokenUsageBar from "./TokenUsageBar.vue";
import CostTable from "./CostTable.vue";

const {
  costs,
  loading,
  error,
  totalCost,
  totalInputTokens,
  totalOutputTokens,
  totalSessions,
  sessionSummaries,
  maxSessionCost,
  expandedSessionId,
  liveCostEvents,
  isConnected,
  fetchCosts,
  toggleSession,
  formatUsd,
  formatTokens,
} = useCosts();
</script>

<template>
  <div class="max-w-6xl mx-auto px-6 py-8">
    <!-- Header -->
    <div class="flex items-center justify-between mb-8">
      <div>
        <h1 class="text-2xl font-semibold text-gray-100">Cost Dashboard</h1>
        <p class="mt-1 text-sm text-gray-500">
          Token usage and cost breakdown across all sessions.
        </p>
      </div>
      <div class="flex items-center gap-3">
        <span
          class="inline-block w-2 h-2 rounded-full"
          :class="isConnected ? 'bg-emerald-400' : 'bg-gray-600'"
        />
        <span class="text-xs text-gray-500">{{ isConnected ? "Live" : "Offline" }}</span>
        <button
          @click="fetchCosts"
          :disabled="loading"
          class="px-4 py-2 text-sm font-medium rounded-lg bg-gray-800 text-gray-300 hover:text-white hover:bg-gray-700 border border-gray-700 disabled:opacity-50 transition-colors"
        >
          {{ loading ? "Loading..." : "Refresh" }}
        </button>
      </div>
    </div>

    <!-- Error -->
    <div
      v-if="error"
      class="rounded-xl bg-red-900/20 border border-red-800/40 px-4 py-3 text-sm text-red-300 mb-6"
    >
      {{ error }}
    </div>

    <!-- Summary cards -->
    <div class="grid grid-cols-3 gap-4 mb-8">
      <div class="rounded-xl border border-gray-800 bg-gray-800 px-6 py-5">
        <p class="text-xs text-gray-500 uppercase tracking-wider mb-2">Total Tokens</p>
        <p class="text-3xl font-bold text-blue-400 font-mono">
          {{ formatTokens(totalInputTokens + totalOutputTokens) }}
        </p>
        <p class="text-xs text-gray-600 mt-1 font-mono">
          {{ formatTokens(totalInputTokens) }} in / {{ formatTokens(totalOutputTokens) }} out
        </p>
      </div>
      <div class="rounded-xl border border-gray-800 bg-gray-800 px-6 py-5">
        <p class="text-xs text-gray-500 uppercase tracking-wider mb-2">Total Cost</p>
        <p class="text-3xl font-bold text-green-400 font-mono">{{ formatUsd(totalCost) }}</p>
        <p class="text-xs text-gray-600 mt-1">across {{ totalSessions }} sessions</p>
      </div>
      <div class="rounded-xl border border-gray-800 bg-gray-800 px-6 py-5">
        <p class="text-xs text-gray-500 uppercase tracking-wider mb-2">Sessions</p>
        <p class="text-3xl font-bold text-blue-400 font-mono">{{ totalSessions }}</p>
        <p class="text-xs text-gray-600 mt-1">
          {{ costs.length }} total entries
        </p>
      </div>
    </div>

    <!-- Empty state -->
    <div
      v-if="costs.length === 0 && !loading"
      class="rounded-xl border border-gray-800 bg-gray-900/50 px-6 py-16 text-center"
    >
      <div class="w-12 h-12 mx-auto mb-4 rounded-xl bg-gray-800 flex items-center justify-center">
        <svg
          class="w-6 h-6 text-gray-500"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          stroke-width="1.5"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
          />
        </svg>
      </div>
      <p class="text-sm text-gray-400">No cost data yet</p>
      <p class="text-xs text-gray-600 mt-1">
        Costs are tracked as the agent makes API calls
      </p>
    </div>

    <template v-if="costs.length > 0">
      <!-- Session bar chart -->
      <div class="mb-8">
        <h2 class="text-sm font-medium text-gray-400 uppercase tracking-wider mb-4">
          Cost by Session
        </h2>
        <div class="space-y-2">
          <div
            v-for="session in sessionSummaries"
            :key="session.sessionId"
            class="group"
          >
            <div
              class="flex items-center gap-3 px-4 py-2 rounded-lg hover:bg-gray-800/40 cursor-pointer transition-colors"
              @click="toggleSession(session.sessionId)"
            >
              <svg
                class="w-3 h-3 text-gray-600 transition-transform duration-200 shrink-0"
                :class="{ 'rotate-90': expandedSessionId === session.sessionId }"
                fill="currentColor"
                viewBox="0 0 20 20"
              >
                <path
                  fill-rule="evenodd"
                  d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                  clip-rule="evenodd"
                />
              </svg>
              <span class="text-xs font-mono text-gray-500 w-28 shrink-0 truncate">
                {{ session.sessionId.slice(0, 12) }}
              </span>
              <div class="flex-1 h-5 bg-gray-800 rounded overflow-hidden">
                <div
                  class="h-full bg-blue-500/60 rounded transition-all duration-500 ease-out"
                  :style="{
                    width: `${Math.max((session.totalCostUsd / maxSessionCost) * 100, 2)}%`,
                  }"
                />
              </div>
              <span class="text-xs font-mono text-gray-400 w-20 text-right shrink-0">
                {{ formatUsd(session.totalCostUsd) }}
              </span>
              <span class="text-xs text-gray-600 w-24 text-right shrink-0">
                {{ session.entries.length }} entries
              </span>
            </div>

            <!-- Expanded session detail -->
            <div
              v-if="expandedSessionId === session.sessionId"
              class="ml-8 mt-1 mb-3 p-4 rounded-lg bg-gray-900/60 border border-gray-800/50"
            >
              <div class="flex items-center gap-6 mb-3 text-xs">
                <div>
                  <span class="text-gray-500">Model:</span>
                  <span class="ml-1 text-gray-300 font-mono">{{ session.model }}</span>
                </div>
                <div>
                  <span class="text-gray-500">Tokens:</span>
                  <span class="ml-1 text-blue-400 font-mono">{{ formatTokens(session.totalInputTokens) }}</span>
                  <span class="text-gray-600 mx-1">/</span>
                  <span class="ml-1 text-emerald-400 font-mono">{{ formatTokens(session.totalOutputTokens) }}</span>
                </div>
              </div>
              <TokenUsageBar
                :input-tokens="session.totalInputTokens"
                :output-tokens="session.totalOutputTokens"
                :height="10"
              />
            </div>
          </div>
        </div>
      </div>

      <!-- Full cost table -->
      <div>
        <h2 class="text-sm font-medium text-gray-400 uppercase tracking-wider mb-4">
          All Entries
        </h2>
        <CostTable :entries="costs" />
      </div>

      <!-- Live events indicator -->
      <div
        v-if="liveCostEvents.length > 0"
        class="mt-6 p-3 rounded-lg border border-gray-800/50 bg-gray-900/30"
      >
        <p class="text-xs text-gray-500">
          <span class="inline-block w-1.5 h-1.5 rounded-full bg-emerald-400 mr-1.5 animate-pulse" />
          {{ liveCostEvents.length }} live cost event{{ liveCostEvents.length === 1 ? "" : "s" }} received this session
        </p>
      </div>
    </template>
  </div>
</template>

// packages/studio/src/components/observability/CostDashboard.tsx
import { useState } from "react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  Legend,
} from "recharts";
import type { CostSummary, CostEntry } from "../../hooks/useObservability";

interface CostDashboardProps {
  costs: CostSummary | null;
  loading: boolean;
  onRefresh: () => void;
  onFilterSession?: (sessionId: string | null) => void;
}

const PIE_COLORS = [
  "#6366f1",
  "#8b5cf6",
  "#a78bfa",
  "#c4b5fd",
  "#e0e7ff",
  "#818cf8",
];

function formatUsd(value: number): string {
  return `$${value.toFixed(4)}`;
}

function formatTokens(value: number): string {
  if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(1)}M`;
  if (value >= 1_000) return `${(value / 1_000).toFixed(1)}K`;
  return String(value);
}

export default function CostDashboard({
  costs,
  loading,
  onRefresh,
  onFilterSession,
}: CostDashboardProps) {
  const [selectedSession, setSelectedSession] = useState<string | null>(null);
  const [view, setView] = useState<"tokens" | "cost">("cost");

  const handleSessionFilter = (sessionId: string | null) => {
    setSelectedSession(sessionId);
    onFilterSession?.(sessionId);
  };

  if (loading && !costs) {
    return (
      <div className="flex h-full items-center justify-center">
        <div className="h-5 w-5 animate-spin rounded-full border-2 border-gray-600 border-t-white" />
      </div>
    );
  }

  if (!costs) {
    return (
      <div className="flex h-full flex-col items-center justify-center gap-3">
        <p className="text-sm text-gray-500">No cost data available</p>
        <button
          onClick={onRefresh}
          className="rounded-md px-3 py-1.5 text-xs text-gray-400 transition-colors hover:bg-gray-800 hover:text-white"
        >
          Refresh
        </button>
      </div>
    );
  }

  const barData = costs.byModel.map((m) => ({
    name: m.model,
    cost: m.costUsd,
    tokens: m.tokens,
  }));

  const pieData = costs.bySession.map((s) => ({
    name: s.sessionId.slice(0, 8),
    value: view === "cost" ? s.costUsd : s.tokens,
    sessionId: s.sessionId,
  }));

  return (
    <div data-testid="cost-dashboard" className="flex h-full flex-col overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-gray-800 px-4 py-3">
        <h2 className="text-sm font-semibold text-white">Cost Dashboard</h2>
        <div className="flex items-center gap-2">
          <button
            onClick={onRefresh}
            disabled={loading}
            className="rounded-md px-2 py-1 text-xs text-gray-400 transition-colors hover:bg-gray-800 hover:text-white disabled:opacity-50"
          >
            {loading ? "Loading..." : "Refresh"}
          </button>
        </div>
      </div>

      {/* Summary cards */}
      <div data-testid="cost-summary" className="grid grid-cols-2 gap-3 border-b border-gray-800 p-4">
        <div className="rounded-lg border border-gray-800 bg-gray-900/50 p-3">
          <p className="text-[10px] uppercase tracking-wider text-gray-500">
            Total Cost
          </p>
          <p className="text-xl font-bold text-white">
            {formatUsd(costs.totalCostUsd)}
          </p>
        </div>
        <div className="rounded-lg border border-gray-800 bg-gray-900/50 p-3">
          <p className="text-[10px] uppercase tracking-wider text-gray-500">
            Total Tokens
          </p>
          <p className="text-xl font-bold text-white">
            {formatTokens(costs.totalTokens)}
          </p>
        </div>
      </div>

      {/* Session filter */}
      {selectedSession && (
        <div className="flex items-center gap-2 border-b border-gray-800 px-4 py-2">
          <span className="text-xs text-gray-500">Filtered by session:</span>
          <span className="font-mono text-xs text-gray-300">
            {selectedSession.slice(0, 12)}
          </span>
          <button
            onClick={() => handleSessionFilter(null)}
            className="text-xs text-red-400 hover:text-red-300"
          >
            Clear
          </button>
        </div>
      )}

      {/* Charts */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {/* View toggle */}
        <div className="flex items-center gap-1 rounded-md bg-gray-900 p-0.5">
          <button
            onClick={() => setView("cost")}
            className={`rounded px-3 py-1 text-xs transition-colors ${
              view === "cost"
                ? "bg-gray-700 text-white"
                : "text-gray-500 hover:text-gray-300"
            }`}
          >
            By Cost
          </button>
          <button
            onClick={() => setView("tokens")}
            className={`rounded px-3 py-1 text-xs transition-colors ${
              view === "tokens"
                ? "bg-gray-700 text-white"
                : "text-gray-500 hover:text-gray-300"
            }`}
          >
            By Tokens
          </button>
        </div>

        {/* Bar chart: cost by model */}
        {barData.length > 0 && (
          <div className="rounded-lg border border-gray-800 bg-gray-900/50 p-4">
            <h3 className="mb-3 text-xs font-medium text-gray-400">
              Cost by Model
            </h3>
            <ResponsiveContainer width="100%" height={200}>
              <BarChart data={barData}>
                <CartesianGrid
                  strokeDasharray="3 3"
                  stroke="#374151"
                  vertical={false}
                />
                <XAxis
                  dataKey="name"
                  tick={{ fontSize: 10, fill: "#9ca3af" }}
                  axisLine={{ stroke: "#374151" }}
                  tickLine={false}
                />
                <YAxis
                  tick={{ fontSize: 10, fill: "#9ca3af" }}
                  axisLine={{ stroke: "#374151" }}
                  tickLine={false}
                  tickFormatter={
                    view === "cost"
                      ? (v: number) => `$${v.toFixed(2)}`
                      : formatTokens
                  }
                />
                <Tooltip
                  contentStyle={{
                    backgroundColor: "#1f2937",
                    border: "1px solid #374151",
                    borderRadius: "6px",
                    fontSize: "11px",
                    color: "#e5e7eb",
                  }}
                  formatter={
                    view === "cost"
                      ? (v: number) => [formatUsd(v), "Cost"]
                      : (v: number) => [formatTokens(v), "Tokens"]
                  }
                />
                <Bar
                  dataKey={view === "cost" ? "cost" : "tokens"}
                  fill="#6366f1"
                  radius={[4, 4, 0, 0]}
                />
              </BarChart>
            </ResponsiveContainer>
          </div>
        )}

        {/* Pie chart: distribution by session */}
        {pieData.length > 0 && (
          <div className="rounded-lg border border-gray-800 bg-gray-900/50 p-4">
            <h3 className="mb-3 text-xs font-medium text-gray-400">
              Distribution by Session
            </h3>
            <ResponsiveContainer width="100%" height={200}>
              <PieChart>
                <Pie
                  data={pieData}
                  cx="50%"
                  cy="50%"
                  innerRadius={40}
                  outerRadius={70}
                  paddingAngle={2}
                  dataKey="value"
                  onClick={(data) => {
                    if (data?.sessionId) {
                      handleSessionFilter(data.sessionId);
                    }
                  }}
                  style={{ cursor: "pointer" }}
                >
                  {pieData.map((_, index) => (
                    <Cell
                      key={`cell-${index}`}
                      fill={PIE_COLORS[index % PIE_COLORS.length]}
                    />
                  ))}
                </Pie>
                <Tooltip
                  contentStyle={{
                    backgroundColor: "#1f2937",
                    border: "1px solid #374151",
                    borderRadius: "6px",
                    fontSize: "11px",
                    color: "#e5e7eb",
                  }}
                  formatter={(v: number) =>
                    view === "cost" ? formatUsd(v) : formatTokens(v)
                  }
                />
                <Legend
                  wrapperStyle={{ fontSize: "10px", color: "#9ca3af" }}
                />
              </PieChart>
            </ResponsiveContainer>
          </div>
        )}

        {/* Turn-level table */}
        {costs.byTurn.length > 0 && (
          <div className="rounded-lg border border-gray-800 bg-gray-900/50">
            <h3 className="border-b border-gray-800 px-4 py-2 text-xs font-medium text-gray-400">
              Per-Turn Breakdown
            </h3>
            <div className="max-h-64 overflow-y-auto">
              <table className="w-full text-xs">
                <thead>
                  <tr className="border-b border-gray-800 text-left text-gray-500">
                    <th className="px-4 py-2 font-medium">Time</th>
                    <th className="px-4 py-2 font-medium">Model</th>
                    <th className="px-4 py-2 text-right font-medium">Prompt</th>
                    <th className="px-4 py-2 text-right font-medium">Completion</th>
                    <th className="px-4 py-2 text-right font-medium">Cost</th>
                  </tr>
                </thead>
                <tbody>
                  {costs.byTurn.map((entry: CostEntry) => (
                    <tr
                      key={entry.id}
                      className="border-b border-gray-800/50 transition-colors hover:bg-gray-800/30"
                    >
                      <td className="px-4 py-2 text-gray-400">
                        {new Date(entry.timestamp).toLocaleTimeString()}
                      </td>
                      <td className="px-4 py-2 text-gray-300">{entry.model}</td>
                      <td className="px-4 py-2 text-right text-gray-400">
                        {formatTokens(entry.promptTokens)}
                      </td>
                      <td className="px-4 py-2 text-right text-gray-400">
                        {formatTokens(entry.completionTokens)}
                      </td>
                      <td className="px-4 py-2 text-right font-medium text-white">
                        {formatUsd(entry.costUsd)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
